import{a as f,i as n,S as m}from"./assets/vendor-D8_O3--j.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function p(r){return f.get("https://pixabay.com/api/",{params:{key:"51402348-a0c5f352e8dacc54a34bc803e",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data.hits.length===0?n.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"}):s.data.hits).catch(s=>{})}let g=new m(".gallery a");function h(r){const s=document.querySelector(".gallery"),a=r.map(i=>{const{webformatURL:e,largeImageURL:t,tags:o,likes:l,views:c,comments:u,downloads:d}=i;return`<li class="img-li">
        <a href="${t}">
        <img src="${e}" alt="${o}" class="img">
        <div class="all-stats">
        <div class="stats"><p class="stats-name">Likes</p><p class="stats-value">${l}</p></div>
        <div class="stats"><p class="stats-name">Views</p><p class="stats-value">${c}</p></div>
        <div class="stats"><p class="stats-name">Comments</p><p class="stats-value">${u}</p></div>
        <div class="stats"><p class="stats-name">Downloads</p><p class="stats-value">${d}</p></div>
        </div>
        </a>
        </li>`}).join("");s.insertAdjacentHTML("beforeend",a),g.refresh()}function y(){document.querySelector(".gallery").innerHTML=""}function v(){document.querySelector(".loader").classList.remove("visually-hidden")}function L(){document.querySelector(".loader").classList.add("visually-hidden")}const b=document.querySelector(".form");b.addEventListener("submit",r=>{r.preventDefault();const s=r.currentTarget.elements["search-text"].value.trim();s&&(v(),y(),p(s).then(a=>h(a)).catch(a=>{if(!a===void 0)return n.show({message:"Error happened",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"})}).finally(()=>{L()}))});
//# sourceMappingURL=index.js.map
