import{a as d,i as m,S as f}from"./assets/vendor-D8_O3--j.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function p(s){return d.get("https://pixabay.com/api/",{params:{key:"51402348-a0c5f352e8dacc54a34bc803e",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>{if(t.data.hits.length===0){m.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040"});return}return t.data.hits}).catch(t=>t)}let g=new f(".gallery a");function y(s){const t=document.querySelector(".gallery"),a=s.map(n=>{const{webformatURL:e,largeImageURL:r,tags:o,likes:c,views:i,comments:l,downloads:u}=n;return`<li class="img-li">
        <a href="${r}">
        <img src="${e}" alt="${o}" class="img">
        <div class="all-stats">
        <div class="stats"><p class="stats-name">Likes</p><p class="stats-value">${c}</p></div>
        <div class="stats"><p class="stats-name">Views</p><p class="stats-value">${i}</p></div>
        <div class="stats"><p class="stats-name">Comments</p><p class="stats-value">${l}</p></div>
        <div class="stats"><p class="stats-name">Downloads</p><p class="stats-value">${u}</p></div>
        </div>
        </a>
        </li>`}).join("");t.insertAdjacentHTML("beforeend",a),g.refresh()}function h(){document.querySelector(".gallery").innerHTML=""}function v(){document.querySelector(".container").insertAdjacentHTML("beforeend","<span class='loader'></span>")}function L(){document.querySelector(".loader").remove()}const b=document.querySelector(".form"),S=document.querySelector(".container");S.insertAdjacentHTML("beforeend","<ul class='gallery'>");b.addEventListener("submit",s=>{s.preventDefault();const t=s.currentTarget.elements["search-text"].value.trim();t&&(v(),h(),p(t).then(a=>y(a)),L())});
//# sourceMappingURL=index.js.map
