import{a as d,i as m,S as f}from"./assets/vendor-D8_O3--j.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function p(r){return d.get("https://pixabay.com/api/",{params:{key:"51402348-a0c5f352e8dacc54a34bc803e",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>{if(t.data.hits.length===0){m.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040"});return}return t.data.hits}).catch(t=>t)}let y=new f(".gallery a");function g(r){const t=document.querySelector(".gallery"),a=r.map(i=>{const{webformatURL:e,largeImageURL:s,tags:o,likes:l,views:n,comments:c,downloads:u}=i;return`<li class="img-li">
        <a href="${s}">
        <img src="${e}" alt="${o}" class="img">
        <div class="all-stats">
        <div class="stats"><p class="stats-name">Likes</p><p class="stats-value">${l}</p></div>
        <div class="stats"><p class="stats-name">Views</p><p class="stats-value">${n}</p></div>
        <div class="stats"><p class="stats-name">Comments</p><p class="stats-value">${c}</p></div>
        <div class="stats"><p class="stats-name">Downloads</p><p class="stats-value">${u}</p></div>
        </div>
        </a>
        </li>`}).join("");t.insertAdjacentHTML("beforeend",a),y.refresh()}function h(){document.querySelector(".gallery").innerHTML=""}function v(){document.querySelector(".loader").classList.remove("visually-hidden")}function L(){document.querySelector(".loader").classList.add("visually-hidden")}const b=document.querySelector(".form");b.addEventListener("submit",r=>{r.preventDefault();const t=r.currentTarget.elements["search-text"].value.trim();t&&(v(),h(),p(t).then(a=>g(a)),L())});
//# sourceMappingURL=index.js.map
